[theme]
# The main color for buttons and widgets
primaryColor="#0068C9"

# The main page background color
backgroundColor="#F0F2F6"

# The sidebar background color
secondaryBackgroundColor="#FFFFFF"

# The color for text
textColor="#0C0C0C"

# Font type
font="sans serif"